### ISSUE TITLE
no question code available in processed data

### ISSUE THREAD

**Issue by cyanbx** [DanielLin94144/DUAL-textless-SQA#3]
Brilliant works! We are trying to train this model and we find that only codes of contexts are provided in the processed data link. Would you mind providing the processed codes of questions of train and dev split? since the preprocess pipeline is a little time consuming.

**Comment by DanielLin94144** [comment]
Hi @cyanbx, thanks for your question. We are sorry that the question code is missing in the original processed data. We have added the question code in (https://ntucc365-my.sharepoint.com/:f:/g/personal/r10942104_ntu_edu_tw/EqXPTZAQJcNGgWP0gLW0FngBmpWSPWEHZ0h-ukEbIleh3g?e=Qv4Bas)
